// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNt-o3Y9F_MCItgnkybgy6NiLVNN1aw3Q',
    appId: '1:541117091434:web:bc780fec61eaf2281e8413',
    messagingSenderId: '541117091434',
    projectId: 'keepnotes---clone',
    authDomain: 'keepnotes---clone.firebaseapp.com',
    storageBucket: 'keepnotes---clone.appspot.com',
    measurementId: 'G-YDLBCCS83X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFEqEmg0Ylg4IIEQzP0iOthVq_4nA9F0M',
    appId: '1:541117091434:android:d9f7e2ff4967a6611e8413',
    messagingSenderId: '541117091434',
    projectId: 'keepnotes---clone',
    storageBucket: 'keepnotes---clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDezSZE5ODA6uXPjryDGf8AriuOWR6EE6g',
    appId: '1:541117091434:ios:94a6be2a2041a3811e8413',
    messagingSenderId: '541117091434',
    projectId: 'keepnotes---clone',
    storageBucket: 'keepnotes---clone.appspot.com',
    iosBundleId: 'com.example.keepNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDezSZE5ODA6uXPjryDGf8AriuOWR6EE6g',
    appId: '1:541117091434:ios:94a6be2a2041a3811e8413',
    messagingSenderId: '541117091434',
    projectId: 'keepnotes---clone',
    storageBucket: 'keepnotes---clone.appspot.com',
    iosBundleId: 'com.example.keepNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNt-o3Y9F_MCItgnkybgy6NiLVNN1aw3Q',
    appId: '1:541117091434:web:f05c62100a32b5f31e8413',
    messagingSenderId: '541117091434',
    projectId: 'keepnotes---clone',
    authDomain: 'keepnotes---clone.firebaseapp.com',
    storageBucket: 'keepnotes---clone.appspot.com',
    measurementId: 'G-C0PSZ1WY06',
  );
}
